---
- name: Install mandatory packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - htop
    - ntp
    - apt-transport-https
    - ca-certificates
    - python-setuptools

- name: Install python package manager
  easy_install:
    name: pip
    state: latest

- name: Install docker engine dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - gnupg2

- name: Install docker engine apt key
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Update docker engine repository url
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo debian-jessie main
    state: present
    update_cache: yes

- name: Install docker engine packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - docker-engine

- name: Install docker python bindings
  pip:
    name: "{{ item }}"
  with_items:
    - docker-py
    - docker-compose
